env:
  browser: true
  es6: true
  node: true
extends: 
- eslint:recommended
- plugin:react/recommended
- plugin:import/errors
- plugin:flowtype/recommended
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - flowtype
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  no-console: 0